#!/bin/bash -ex
# executed after apply-overlay

source $(dirname $0)/functions

# protect drupal7.conf from prying eyes
chmod 600 /etc/dbconfig-common/drupal7.conf

# generate dbconfig for drupal7
# drush does not use dbconfig.php, but edits settings.php directly
# Leaving this here now for compatibility ???
# dbconfig-generate-include -f php -O root:www-data -m 640 /etc/dbconfig-common/drupal7.conf /etc/drupal7/sites/default/dbconfig.php

# install uploadprogress bar (from PECL) (requested by Drupal 7)
pecl install uploadprogress
echo "extension = uploadprogress.so" > /etc/php5/apache2/conf.d/uploadprogress.ini

# configure apache
ln -s /etc/drupal7/apache2.conf /etc/apache2/sites-available/drupal7
a2dissite default
a2ensite drupal7
a2enmod rewrite substitute

# increase php's 'memory_limit' from 32MB to 96MB/128MB
CONF=/etc/php5/apache2/php.ini
sed -i "s/^memory_limit.*/memory_limit = 96M/" $CONF

CONF=/etc/php5/cli/php.ini
sed -i "s/^memory_limit.*/memory_limit = 128M/" $CONF

# install drupal site using 'standard' profile
. /etc/dbconfig-common/drupal7.conf

# drush site installation
drush site-install standard -y --account-name=Admin --site-name=Drupal7 --db-su=root --db-su-pw='' --db-url=$dbc_dbtype://$dbc_dbuser:$dbc_dbpass@localhost/$dbc_dbname

# install additional modules
xargs -a $(dirname $0)/add_modules drush pm-download

# set private file path
drush variable-set --always-set file_private_path "/var/lib/drupal7/private"

# install ckeditor backend
drush -y pm-enable ckeditor
drush ckeditor-download

# setup getid3 module
# patch getid3 to change 'error' to 'warning', else install aborts.
MOD_DIR=/etc/drupal7/sites/all/modules
sed -i "/drupal_set_message/ s/error/warning/" $MOD_DIR/getid3/getid3.module

drush -y pm-enable getid3
drush getid3-download

# enable backup&migrate module
drush -y pm-enable backup_migrate

# chown all modules/libraries (they come with their own permissions)
chown -R root:root /etc/drupal7/sites/all

# add some useful aliases
sed -i -e '/alias egrep/a\
    alias ll="ls -alh --color=auto"\
    alias la="ls -A --color=auto"\
    alias l="ls -C --color=auto"
' ~/.bashrc

cat >> /etc/aliases << EOF
webmaster:     root
abuse:         root
#root:         <admin e-mail address>
EOF

# change turnkey version
sed -i -e 's/lamp/drupal7/' /etc/turnkey_version

# stop mysql server
stop mysql

# tell the world what we've done!
echo 'TurnKey Drupal7 Appliance + Drush' >> /etc/issue
