#!/bin/bash -ex
# executed before apply-overlay

source $(dirname $0)/functions

# create the desired directory structure for drupal 7
mkdir -p /usr/share/drupal7
mkdir -p /etc/drupal7/sites/all/libraries
mkdir -p /etc/drupal7/sites/default
mkdir -p /etc/drupal7/profiles
ln -s /etc/drupal7/sites /usr/share/drupal7/
ln -s /etc/drupal7/profiles /usr/share/drupal7/

# create directories for public and private files
mkdir -p /var/lib/drupal7/files
mkdir -p /var/lib/drupal7/private
chown -R www-data:www-data /var/lib/drupal7
chmod -R 2770 /var/lib/drupal7
ln -s /var/lib/drupal7/files /usr/share/drupal7/
ln -s /var/lib/drupal7/files /etc/drupal7/sites/default/

# create helpful symlinks
ln -s /usr/share/drupal7 /var/www/webroot
ln -s /etc/drupal7 /var/www/config

