#!/bin/bash -ex
# executed before apply-overlay

source $(dirname $0)/functions

# use drush to download latest stable version of drupal 7
drush --destination=/usr/share pm-download drupal --default-major=7 --drupal-project-rename=drupal7
chown -R root:root /usr/share/drupal7

# create the desired directory structure for drupal 7
mkdir -p /etc/drupal7
mv /usr/share/drupal7/.htaccess /etc/drupal7/htaccess
ln -s /etc/drupal7/htaccess /usr/share/drupal7/.htaccess
mv /usr/share/drupal7/sites /etc/drupal7/
ln -s /etc/drupal7/sites /usr/share/drupal7/
mv /usr/share/drupal7/profiles /etc/drupal7/
ln -s /etc/drupal7/profiles /usr/share/drupal7/
mkdir -p /etc/drupal7/sites/all/libraries

# create directories for public and private files
mkdir -p /var/lib/drupal7/files
mkdir -p /var/lib/drupal7/private
chown -R www-data:www-data /var/lib/drupal7
chmod -R 2770 /var/lib/drupal7
ln -s /var/lib/drupal7/files /usr/share/drupal7/
ln -s /var/lib/drupal7/files /etc/drupal7/sites/default/

# create helpful symlinks
ln -s /usr/share/drupal7 /var/www/webroot
ln -s /etc/drupal7 /var/www/config

# protect Drupal settings from prying eyes
SETTINGS=/etc/drupal7/sites/default/settings.php
cp /etc/drupal7/sites/default/default.settings.php $SETTINGS
chown root:www-data $SETTINGS
chmod 640 $SETTINGS

# Disable Poor Man's Cron
cat >> $SETTINGS << EOF

/**
 * Disable Poor Man's Cron:
 *
 * Drupal 7 enables the built-in Poor Man's Cron by default.
 * Poor Man's Cron relies on site activity to trigger Drupal's cron,
 * and is not well suited for low activity websites.
 *
 * We will use the Linux system cron and override Poor Man's Cron
 * by setting the cron_safe_threshold to 0.
 *
 * To re-enable Poor Man's Cron:
 *    Comment out (add a leading hash sign) the line below,
 *    and the system cron in /etc/cron.d/drupal7.
 */
\$conf['cron_safe_threshold'] = 0;
EOF

