#!/bin/bash -ex
# executed before apply-debs

source $(dirname $0)/functions

# install security updates
# better to do them here once than force every user later
install_updates

# install packages required by Drupal7 and Drush
# php-getid3          /* dependency of drupal module getid3 */
# php5-cli            /* dependency of drupal shell drush */
# php5-curl           /* dependency of drupal module simpletest */
# php-pear, make      /* dependency of drupal7 PECL */
# subversion          /* dependency of drush ckeditor-download */
# wwwconfig-common    /* de[emdemcu of drush */

install php5 php5-cli php5-curl php5-gd php5-dev php5-xcache php-pear make subversion wwwconfig-common

# remove old kernel images after update
cleanup_images

# start mysql server
start mysql

